@API_URL = http://localhost:8080
###   - https://womp1loginapi.onrender.com
@DEV_TOKEN = {{${{$dotenv DEV_TOKEN}}}}

###Create new user
POST {{API_URL}}/users
Content-Type: application/json

{
    "username": "trial5",
    "password": "yaes"
}

###Testar GET
GET {{API_URL}}/users

{

}

### Login
POST {{API_URL}}/users/login
Content-Type: application/json

{
    "username": "testerForFredde",
    "password": "5432WoM"
}