@API_URL = http://localhost:8080
@DEV_TOKEN = {{${{$dotenv DEV_TOKEN}}}}

###Create new user
POST {{API_URL}}/users
Content-Type: application/json

{
    "username": "aaro",
    "password": "js246"
}

### Login
POST {{API_URL}}/users/login
Content-Type: application/json

{
    "username": "aaro",
    "password": "js246"
}