services:
  node-app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8081"
    environment:
      - MODE
      - DATABASE_URL
      - JWT_STRING
